### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by xzebra** [katharostech/bevy_retro#9]
This might be related to #7, but I've tried to integrate bevy_retro into my project but I'm getting the same error the mentioned issue got:
```
    ... required by package `luminance-glow v0.0.0 (https://github.com/katharostech/luminance-glow?branch=master#ca5a0b62)`
    ... which is depended on by `bevy_retro_core v0.0.0 (https://github.com/katharostech/bevy_retro?branch=master#a3086444)`
    ... which is depended on by `bevy_retro v0.0.0 (https://github.com/katharostech/bevy_retro?branch=master#a3086444)`
    ... which is depended on by `zworld v0.1.0 (/home/zebra/projects/zworld-rs)`
versions that meet the requirements `^0.3.48` are: 0.3.50, 0.3.49, 0.3.48

all possible versions conflict with previously selected packages.

  previously selected package `web-sys v0.3.46`
    ... which is depended on by `bevy_app v0.5.0`
    ... which is depended on by `bevy_asset v0.5.0`
    ... which is depended on by `bevy_audio v0.5.0`
    ... which is depended on by `bevy_internal v0.5.0`
    ... which is depended on by `bevy v0.5.0`
    ... which is depended on by `zworld v0.1.0 (/home/zebra/projects/zworld-rs)`
```
As the issue said, I tried to `cargo update` with no success. My `Cargo.toml` looks like this:
```toml
[dependencies]
bevy = "0.5"
bevy_retro = { git = "https://github.com/katharostech/bevy_retro", branch="master" }
bevy_tilemap = { git = "https://github.com/joshuajbouw/bevy_tilemap", branch="master" }
```
